name: mysql-docker-template

services:
  mysql:
    build: 
      context: ./.docker/mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    configs:
      - source: mysql_config
        target: /etc/mysql/my.cnf
    secrets:
      - mysql_database
      - mysql_root_password
      - mysql_user
      - mysql_password
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=`cat /run/secrets/mysql_root_password` | grep 'mysqld is alive'"]
      interval: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - migrator-tier
      - phpmyadmin-tier

  migrator:
    build:
      context: ./.docker/migrator
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    secrets:
      - mysql_root_password
      - mysql_database
    networks:
      - migrator-tier
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
      UPLOAD_LIMIT: 50M
    secrets:
      - mysql_root_password
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - phpmyadmin-tier
    depends_on:
      mysql:
        condition: service_healthy
          
configs:
  mysql_config:
    file: ./.docker/mysql/config/my.cnf

secrets:
  mysql_database:
    file: ./.docker/mysql/secrets/database.txt
  mysql_root_password:
    file: ./.docker/mysql/secrets/root_password.txt
  mysql_user:
    file: ./.docker/mysql/secrets/user.txt
  mysql_password:
    file: ./.docker/mysql/secrets/password.txt

volumes:
  mysql-data: {}
      
networks:
  migrator-tier: {}
  phpmyadmin-tier: {}
