version: "3.9"

services:
  mysql:
    build: 
      context: ./docker/mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_database
      - mysql_root_password
      - mysql_user
      - mysql_password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=`cat /run/secrets/mysql_root_password` | grep 'mysqld is alive'"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql-store:/var/lib/mysql
    networks:
      - migrator-network
      - phpmyadmin-network

  migrator:
    build:
      context: ./docker/migrator
    container_name: migrator
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    secrets:
      - mysql_root_password
      - mysql_database
    networks:
      - migrator-network
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
      UPLOAD_LIMIT: 50M
    secrets:
      - mysql_root_password
    ports:
      - 8080:80
    networks:
      - phpmyadmin-network
    depends_on:
      mysql:
        condition: service_healthy

secrets:
  mysql_database:
    file: ./docker/mysql/secrets/database.txt
  mysql_root_password:
    file: ./docker/mysql/secrets/root_password.txt
  mysql_user:
    file: ./docker/mysql/secrets/user.txt
  mysql_password:
    file: ./docker/mysql/secrets/password.txt

volumes:
  mysql-store:
      
networks:
  migrator-network:
  phpmyadmin-network:
