version: "3.9"

services:
  mysql:
    build: 
      context: ./docker/mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: template
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-store:/var/lib/mysql
    networks:
      - phpmyadmin-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
      UPLOAD_LIMIT: 50M
    secrets:
      - mysql_root_password
    ports:
      - 8080:80
    networks:
      - phpmyadmin-network
    depends_on:
      mysql:
        condition: service_healthy

secrets:
  mysql_root_password:
    file: ./docker/mysql/secrets/mysql_root_password.txt
  mysql_user:
    file: ./docker/mysql/secrets/mysql_user.txt
  mysql_password:
    file: ./docker/mysql/secrets/mysql_password.txt

volumes:
  mysql-store:
      
networks:
  phpmyadmin-network: