version: "3.9"

services:
  mysql:
    build: 
      context: ./docker/mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: template
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-store:/var/lib/mysql
    networks:
      - phpmyadmin-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 50M
    ports:
      - 8080:80
    networks:
      - phpmyadmin-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-store:
      
networks:
  phpmyadmin-network: